spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&autoReconnect=false&rewriteBatchedStatements=true  &serverTimezone=GMT
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true