@startuml
left to right direction
actor User as u

package 绑定的手机号-未注册 {
    usecase "绑定手机号" as change1
    usecase "触发帐号合并" as mobile1
    change1 --> mobile1: include
}

package 绑定的手机号-已注册-不是本人注册 {
    usecase "绑定手机号" as change2
    usecase "触发帐号合并" as mobile2

    change2 -->  mobile2: include
    note right of mobile2: 合并到新注册的帐号上
    change2 --> (手机号注册新的帐号): include
    change2 --> (帐号降级 \n手机号对应的帐号): include
}

package 绑定的手机号-已注册-本人注册 {
    usecase "绑定手机号" as change3
    usecase "触发帐号合并" as mobile3

    change3 --> mobile3: include

    change3 --> (冲突的平台帐号解绑): include
    note right of (冲突的平台帐号解绑): 手机号对应的帐号，\n解绑【冲突】的平台帐号
}

u --> change1: extend
u --> change2: extend
u --> change3: extend

@enduml


@startuml
left to right direction
skinparam packageStyle rectangle

actor 业务岗
note left of 业务岗
  平台、核心企业、供应商、
  保理/金融机构有业务岗
end note

actor 风控岗
note left of 风控岗
  平台、核心企业、供应商、
  保理/金融机构有风控岗
end note

actor 财务岗
note left of 财务岗
  平台、核心企业、供应商、
  保理/金融机构有财务岗
end note

rectangle 银票系统 {
  业务岗 -- (开户)
  业务岗 -- (用户注册)
  业务岗 -- (登录)
  业务岗 -- (银票开立)
  业务岗 -- (银票融资)
  业务岗 -- (银票转让)

  (开户) --> (企业信息) : include
  (开户) --> (开通账号) : include
  (开户) --> (绑定UKey) : include

  (用户注册) --> (打开邀请链接) : include
  (用户注册) --> (完善企业信息) : include
  (用户注册) --> (审核流程) : include
  (用户注册) --> (授信) : include

  (银票开立) --> (申请开立银票) : include
  (银票开立) --> (审核流程) : include
  (银票开立) --> (结算) : include

  (银票融资) --> (创建融资单) : include
  (银票融资) --> (审核流程) : include
  (银票融资) --> (融资确认) : include
  (银票融资) --> (融资放款) : include
  (银票融资) --> (结算) : include

  (银票转让) --> (审核流程) : include
  (银票转让) --> (延期) : include


  (开通账号) --> (通知) : include
  (企业信息) --> (录入企业信息) : include
  (企业信息) --> (验证企业信息) : include
  (授信) --> (保理公司授信) : include
  (授信) --> (验证上游授信额度) : include
  (授信) --> (调整上级供应商/核心企业授信额度) : include
  (申请开立银票) --> (提交应收帐款等资料) : include
  (审核流程) --> (审核): include
  (延期) --> (结算) : include

  (结算) --> (计息) : include

  (通知) <|-- (短信通知)
  (通知) <|-- (邮件通知)

  (验证上游授信额度) <|-- (验证核心企业授信额度) : include
  (验证上游授信额度) <|-- (验证上级供应商授信额度) : include

  (计息) <|-- (银票融资计息)
  (计息) <|-- (延期计息)
  (计息) <|-- (逾期罚息)

  (审核) <|-- (平台业务/财务/风控审核)
  (审核) <|-- (核心企业业务/财务/风控审核)
  (审核) <|-- (供应商业务/财务/风控审核)
  (审核) <|-- (保理/金融业务/财务/风控审核)

  [业务核心接口模块] -left--> 业务核心
}

note left of 业务核心
  所有外部接口均由业务核心提供
  包括银行类接口、统一用户信息接口等
  该部分接口已ready（但和已有参照代码的接口完全不兼容）
end note

node 业务核心 {
  () "充值接口"
  () "提现接口"
  () "放款接口"
  () "还款接口"
  () "银行账户信息校验接口"
  () "用户开户接口"
  () "用户信息设置接口"
  () "用户信息查询接口"
}

@enduml


@startuml
actor foo
foo --> (bar) : normal
foo --> (bar1) #line:red;line.bold;text:red  : red bold
foo --> (bar2) #green;line.dashed;text:green : green dashed
foo --> (bar3) #blue;line.dotted;text:blue   : blue dotted
@enduml


@startuml
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor 管理员
note left of 管理员
  数环员工
end note


actor 用户
管理员 --> 用户 : include


rectangle 数环产品用例 {
    用户 --> (用户注册)
    用户 --> (创建机构与组织)
    用户 --> (组织授权与管理)
    用户 --> (修改密码)
    用户 --> (登录)
    用户 --> (添加用户（保存授权信息）)
    用户 --> (保存流程)
    用户 --> (选购商品)#line:red;line.bold;text:red
    用户 --> (支付订单)#line:red;line.bold;text:red


    管理员 --> (配置连接器) #green;line.dashed;text:green
    管理员 --> (保存流程模板)
    管理员 --> (查询监控日志) #green;line.dashed;text:green


    (用户注册) --> (审核流程)  #green;line.dashed;text:green : include
    (用户注册) --> (完善企业信息) #green;line.dashed;text:green : include
    (用户注册) --> (完善帐号密码信息) : include
    (用户注册) --> (打开注册页面) : include

    (支付订单) --> (初始化实例和功能) #line:red;line.bold;text:red : include
    (支付订单) --> (支付（支付渠道）) #line:red;line.bold;text:red : include
    (选购商品) --> (下单（包含续费）) #line:red;line.bold;text:red : include


    (登录)  --> (图形验证码，滑块，防撞库等安全校验) #green;line.dashed;text:green : include
    (登录)  --> (短信验证码校验) : include
    (登录)  --> (密码校验) : include
}
@enduml



@startuml
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor 用户

rectangle 数环产品用例 {
    用户 --> (下载浏览器插件)
    用户 --> (安装浏览器插件)
    用户 --> (插件注册和登录)
    用户 --> (使用浏览器插件)


    (使用浏览器插件) --> (浏览器操作)  #red;text:red : include
    (使用浏览器插件) --> (网页操作) #red;text:red : include

    (浏览器操作) --> (打开新的窗口/标签) : include
    (浏览器操作) --> (切换标签) : include
    (浏览器操作) --> (关闭窗口/标签) : include
    (浏览器操作) --> (网页前进) : include
    (浏览器操作) --> (网页后退) : include
    (浏览器操作) --> (刷新页面) : include
    (网页操作) --> (点击网页元素) : include
    (网页操作) --> (获取元素文本) : include
    (网页操作) --> (模拟按键输入) : include
    (网页操作) --> (滚动网页) : include
    (网页操作) --> (模拟翻页) : include


}
@enduml